name: DailyBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --manifest-path ./rikicad/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path ./rikicad/Cargo.toml --verbose
